// SPDX-FileCopyrightText: Copyright (c) 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------------------------//
// Auto-generated by gen_lfsr.py
//------------------------------------------------------------------------------------------------//

// CRC polynomial: 0x10000001 (normal)

module prbs_lfsr_hc # (
    parameter DATA_WIDTH = 8
) (
    input  [DATA_WIDTH-1:0] data_in,
    input  [30:0]           state_in,
    output [30:0]           state_out
);

logic [DATA_WIDTH-1:0] din;
logic [30:0]           lfsr_q;
logic [30:0]           lfsr_c;

generate
  if (DATA_WIDTH==8) begin
    assign lfsr_c[0] = lfsr_q[20] ^ lfsr_q[23] ^ din[7];
    assign lfsr_c[1] = lfsr_q[21] ^ lfsr_q[24] ^ din[6];
    assign lfsr_c[2] = lfsr_q[22] ^ lfsr_q[25] ^ din[5];
    assign lfsr_c[3] = lfsr_q[23] ^ lfsr_q[26] ^ din[4];
    assign lfsr_c[4] = lfsr_q[24] ^ lfsr_q[27] ^ din[3];
    assign lfsr_c[5] = lfsr_q[25] ^ lfsr_q[28] ^ din[2];
    assign lfsr_c[6] = lfsr_q[26] ^ lfsr_q[29] ^ din[1];
    assign lfsr_c[7] = lfsr_q[27] ^ lfsr_q[30] ^ din[0];
    assign lfsr_c[8] = lfsr_q[0];
    assign lfsr_c[9] = lfsr_q[1];
    assign lfsr_c[10] = lfsr_q[2];
    assign lfsr_c[11] = lfsr_q[3];
    assign lfsr_c[12] = lfsr_q[4];
    assign lfsr_c[13] = lfsr_q[5];
    assign lfsr_c[14] = lfsr_q[6];
    assign lfsr_c[15] = lfsr_q[7];
    assign lfsr_c[16] = lfsr_q[8];
    assign lfsr_c[17] = lfsr_q[9];
    assign lfsr_c[18] = lfsr_q[10];
    assign lfsr_c[19] = lfsr_q[11];
    assign lfsr_c[20] = lfsr_q[12];
    assign lfsr_c[21] = lfsr_q[13];
    assign lfsr_c[22] = lfsr_q[14];
    assign lfsr_c[23] = lfsr_q[15];
    assign lfsr_c[24] = lfsr_q[16];
    assign lfsr_c[25] = lfsr_q[17];
    assign lfsr_c[26] = lfsr_q[18];
    assign lfsr_c[27] = lfsr_q[19];
    assign lfsr_c[28] = lfsr_q[20];
    assign lfsr_c[29] = lfsr_q[21];
    assign lfsr_c[30] = lfsr_q[22];
  end
  else if (DATA_WIDTH==16) begin
    assign lfsr_c[0] = lfsr_q[12] ^ lfsr_q[15] ^ din[15];
    assign lfsr_c[1] = lfsr_q[13] ^ lfsr_q[16] ^ din[14];
    assign lfsr_c[2] = lfsr_q[14] ^ lfsr_q[17] ^ din[13];
    assign lfsr_c[3] = lfsr_q[15] ^ lfsr_q[18] ^ din[12];
    assign lfsr_c[4] = lfsr_q[16] ^ lfsr_q[19] ^ din[11];
    assign lfsr_c[5] = lfsr_q[17] ^ lfsr_q[20] ^ din[10];
    assign lfsr_c[6] = lfsr_q[18] ^ lfsr_q[21] ^ din[9];
    assign lfsr_c[7] = lfsr_q[19] ^ lfsr_q[22] ^ din[8];
    assign lfsr_c[8] = lfsr_q[20] ^ lfsr_q[23] ^ din[7];
    assign lfsr_c[9] = lfsr_q[21] ^ lfsr_q[24] ^ din[6];
    assign lfsr_c[10] = lfsr_q[22] ^ lfsr_q[25] ^ din[5];
    assign lfsr_c[11] = lfsr_q[23] ^ lfsr_q[26] ^ din[4];
    assign lfsr_c[12] = lfsr_q[24] ^ lfsr_q[27] ^ din[3];
    assign lfsr_c[13] = lfsr_q[25] ^ lfsr_q[28] ^ din[2];
    assign lfsr_c[14] = lfsr_q[26] ^ lfsr_q[29] ^ din[1];
    assign lfsr_c[15] = lfsr_q[27] ^ lfsr_q[30] ^ din[0];
    assign lfsr_c[16] = lfsr_q[0];
    assign lfsr_c[17] = lfsr_q[1];
    assign lfsr_c[18] = lfsr_q[2];
    assign lfsr_c[19] = lfsr_q[3];
    assign lfsr_c[20] = lfsr_q[4];
    assign lfsr_c[21] = lfsr_q[5];
    assign lfsr_c[22] = lfsr_q[6];
    assign lfsr_c[23] = lfsr_q[7];
    assign lfsr_c[24] = lfsr_q[8];
    assign lfsr_c[25] = lfsr_q[9];
    assign lfsr_c[26] = lfsr_q[10];
    assign lfsr_c[27] = lfsr_q[11];
    assign lfsr_c[28] = lfsr_q[12];
    assign lfsr_c[29] = lfsr_q[13];
    assign lfsr_c[30] = lfsr_q[14];
  end
  else begin
    assign lfsr_c = lfsr_q;
  end
endgenerate


genvar i,j;
for (i=0;i<31;i=i+1) begin
  assign state_out[i] = lfsr_c[i];
  assign lfsr_q[i]    = state_in[i];
end

for (j=0;j<DATA_WIDTH;j=j+1) begin
  assign din[j]       = data_in[j];
end

endmodule
