# syntax=docker/dockerfile:1

# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG CONTAINER_VERSION=invalid
ARG APT_CACHE_MOUNT="--mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked"

FROM ${CONTAINER_VERSION} AS base

RUN ${APT_CACHE_MOUNT} apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
    wget \
    pkg-config \
    libibverbs-dev \
    libnuma-dev \
    libnvtoolsext1 \
    libvulkan1 \
    libelf-dev \
    python3 \
    python3-pip \
  && rm -rf /var/lib/apt/lists/*

RUN curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb \
  && dpkg -i cuda-keyring_1.1-1_all.deb \
  && rm cuda-keyring_1.1-1_all.deb

RUN pip3 install holoscan==4.0.0 cuda-python

ARG HOLOLINK_VERSION=invalid
ARG ARCH=invalid
COPY --from=hololink-package hololink-core_${HOLOLINK_VERSION}_${ARCH}.deb .
COPY --from=hololink-package hololink-dev_${HOLOLINK_VERSION}_${ARCH}.deb .
COPY --from=hololink-package hololink-roce_${HOLOLINK_VERSION}_${ARCH}.deb .

RUN ${APT_CACHE_MOUNT} apt-get update \
 && apt-get install -y ./hololink-core_${HOLOLINK_VERSION}_${ARCH}.deb ./hololink-dev_${HOLOLINK_VERSION}_${ARCH}.deb \
 && rm -rf /var/lib/apt/lists/*
